version: '3.8'

services:
  goserver:
    build: .
    ports:
      - "8080:8080"
    environment:
      - CGO_ENABLED=1
      - CC=gcc
    command: ["go", "run", "cmd/goserver/main.go"]


 